### ISSUE TITLE
Update Thruway dependency to 0.3

### ISSUE THREAD

**Issue by xtrasmal** [Vinelab/minion#5]
Hi there,

The Thruway package is in another version than the one minion requires.
Could you update and test and see if the new version is compatible?

``` "voryx/thruway": "0.3.*" ```

**Comment by douglasgalico** [comment]
Agreed, this is very important. One of the advantages may be the use of addInternalClient method...for example to make a 'Push Server' with a custom Client listening messages from another script (with ZeroQM) and push to topics in a synchronous way.
Maybe this change will result in a new feature like extend Client?
