### ISSUE TITLE
i can't understand your document!

### ISSUE THREAD

**Issue by mb-programmer** [Vinelab/minion#7]
hi
i am building an real time app using Laravel and Wamp2
i used voryx/Thruway for Wamp2 router and wampy.js for browser and your lib for php client
and i actually don't understand your documents
can you be more clear in document? and write about codes should be in which file and what it's the way i should start using this lib.
or better give us one simple Laravel app code to see and explore.

thanks.

**Comment by Mulkave** [comment]
@mb-programmer sorry to hear you're having difficulties understanding the documentation, will do my best to provide a Laravel application example by end of day.

Meanwhile, I'm assuming that you've installed Minion with Laravel 5 and ran `php artisan vendor:publish` to get the configuration file `minion.php` in your config folder which should look something likes this:

```php
return [

    'realm' => 'myrealm',
    'host' => 'localhost',
    'port' => 8000,
    'providers' => [

        'App\RealTime\Providers\MyProvider',
    ],
    'debug' => false,
];
```

Make sure that you change the values according to your router.

- The provider should be at `app/RealTime/Providers/MyProvider.php` and look something like this file https://github.com/Vinelab/minion/blob/master/Examples/basic/DummyProvider.php

- In a Terminal session run `php artisan minion:run` and you should be good to go, your provider has to register/pub/sub methods to be called by your `wampy.js`.

If you need help further please let me know.

**Comment by mb-programmer** [comment]
thanks
and sorry i didn't mention it before i am using Laravel  4.2 in my application.
i am waiting to see your sample app.
