### ISSUE TITLE
How to publish from a controller

### ISSUE THREAD

**Issue by patricknazar** [Vinelab/minion#9]
I know this isn't a bug, but I've worked it all out except how to publish from a controller, not the Service Provider. There may be a gap in my understanding but how do I do it? For example when a user's details are updated, I'd like to send a broadcast to anyone watching that.

Thanks

**Comment by Mulkave** [comment]
Unfortunately at the moment the functionality is not exposed to controllers. A workaround for that would be to instantiate a provider inside the controller (better inject it as a dependency), then call the `boot` method on it, and call `sendMessage($args, $data)`.

PS: Not sure if this will surely work, just suggesting 😄 . If you figure out a better way please share, or even better a PR is much appreciated.

**Comment by teamworktf** [comment]
So from my understanding there is physicial seperation between your PHP web-app and the Minion deamon running for the websocket.

Would something like ZeroMQ suffice as an interaction layer between those two?

**Comment by Mulkave** [comment]
@teamworktf Can you please clarify what you mean by "physicial seperation between your PHP web-app and the Minion deamon"?
